language: c
dist: bionic
sudo: false
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - libavutil-dev
    - libavformat-dev
    - libavcodec-dev
    - libswscale-dev
    - libavdevice-dev

script: ./bootstrap && ./configure && make test
